trigger: none

# The `resources` specify the location and version of the 1ES pipeline template.
resources:
  repositories:
  - repository: 1esPipelines
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  # The pipeline extends the 1ES template which will inject different SDL and compliance tasks.
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1esPipelines
  parameters:
    pool:
      name: VSEngSS-MicroBuild2019-1ES
    stages:
    - stage: Stage
      jobs:
      - job: HostJob
        templateContext:
          outputs:
          - output: pipelineArtifact
            targetPath: $(System.DefaultWorkingDirectory)\$(BuildConfiguration)\*.msi
        steps:
        - checkout: self
          clean: true
          fetchTags: true
        - task: ms-vseng.MicroBuildTasks.30666190-6959-11e5-9f96-f56098202fef.MicroBuildSigningPlugin@1
          displayName: Install Signing Plugin
          inputs:
            signType: real
        - task: NuGetCommand@2
          displayName: Restore NuGet Packages
          inputs:
            solution: setup\*.sln
            feedRestore: 795cdb14-9c0f-490d-965b-8b2799c1b60a
        - task: VSBuild@1
          displayName: Build Solution
          inputs:
            solution: setup\*.sln
            vsVersion: 16.0
            platform: $(BuildPlatform)
            configuration: $(BuildConfiguration)
